/*
Hanuman Sánchez CI: 28.316.086
Anthony Moreno CI: 28.204.620
Angel Goyo CI: 29.737.583
Miller Arias CI: 29.561.941
Luis Ochoa CI: 29.778.672
*/
package ucla.lab.notarius.views;

/**
 *
 * @author ANGELITE
 */
public class AdminGestionMateriaView extends javax.swing.JPanel {

    /**
     * Creates new form LoginView
     */
    public AdminGestionMateriaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMateria = new javax.swing.JTable();
        textFieldBuscarMat = new javax.swing.JTextField();
        buttonVolverMat = new javax.swing.JButton();
        buttonBuscarMat = new javax.swing.JButton();
        panelMateria = new javax.swing.JPanel();
        textFieldNombreMat = new javax.swing.JTextField();
        labelMateriaText2 = new javax.swing.JLabel();
        textFieldApellidoMat = new javax.swing.JTextField();
        comboBoxDecanatoMat = new javax.swing.JComboBox<>();
        comboBoxCarreraMat = new javax.swing.JComboBox<>();
        comboBoxSemestreMat = new javax.swing.JComboBox<>();
        comboBoxProfesorMat = new javax.swing.JComboBox<>();
        buttonAgregarMat = new javax.swing.JButton();
        ComboBoxParaFiltrarMat = new javax.swing.JComboBox<>();
        labelUserMateriaText1 = new javax.swing.JLabel();
        buttonActualizarMat = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(840, 631));

        tableMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "5", null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Materia", "Materia", "Decanato", "Carrera", "Semestre", "Profesor", "..."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMateria);

        textFieldBuscarMat.setText("Buscar...");
        textFieldBuscarMat.setBorder(new javax.swing.border.MatteBorder(null));
        textFieldBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarMatActionPerformed(evt);
            }
        });

        buttonVolverMat.setText("VOLVER");
        buttonVolverMat.setBorder(new javax.swing.border.MatteBorder(null));

        buttonBuscarMat.setText("Buscar");
        buttonBuscarMat.setBorder(new javax.swing.border.MatteBorder(null));

        panelMateria.setBackground(new java.awt.Color(153, 153, 153));
        panelMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFieldNombreMat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codigo de Materia ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldNombreMat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                textFieldNombreMatAncestorRemoved(evt);
            }
        });
        textFieldNombreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreMatActionPerformed(evt);
            }
        });

        labelMateriaText2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMateriaText2.setText("REGISTRO");

        textFieldApellidoMat.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textFieldApellidoMat.setToolTipText("");
        textFieldApellidoMat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldApellidoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidoMatActionPerformed(evt);
            }
        });

        comboBoxDecanatoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DECANATO", "DCyT", "UNAM", " ", " " }));

        comboBoxCarreraMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRERA", "Matematicas II", "Ingles ", "Administracion", " " }));
        comboBoxCarreraMat.setToolTipText("");
        comboBoxCarreraMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCarreraMatActionPerformed(evt);
            }
        });

        comboBoxSemestreMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMESTRE", "1", "2", "3", "4" }));
        comboBoxSemestreMat.setToolTipText("");

        comboBoxProfesorMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROFESOR", "MIGUEL VIVAS", "ANTONI ROGELIO", " " }));
        comboBoxProfesorMat.setToolTipText("");

        javax.swing.GroupLayout panelMateriaLayout = new javax.swing.GroupLayout(panelMateria);
        panelMateria.setLayout(panelMateriaLayout);
        panelMateriaLayout.setHorizontalGroup(
            panelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMateriaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldNombreMat, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(textFieldApellidoMat))
                    .addGroup(panelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxProfesorMat, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE)
                        .addComponent(comboBoxSemestreMat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxCarreraMat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxDecanatoMat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMateriaLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(labelMateriaText2)
                .addGap(63, 63, 63))
        );
        panelMateriaLayout.setVerticalGroup(
            panelMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMateriaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelMateriaText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBoxDecanatoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCarreraMat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSemestreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxProfesorMat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        buttonAgregarMat.setText("Agregar");
        buttonAgregarMat.setBorder(new javax.swing.border.MatteBorder(null));
        buttonAgregarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarMatActionPerformed(evt);
            }
        });

        ComboBoxParaFiltrarMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por", "DECANATO", " " }));
        ComboBoxParaFiltrarMat.setToolTipText(""); // NOI18N
        ComboBoxParaFiltrarMat.setBorder(new javax.swing.border.MatteBorder(null));
        ComboBoxParaFiltrarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxParaFiltrarMatActionPerformed(evt);
            }
        });

        labelUserMateriaText1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUserMateriaText1.setText("GESTION DE MATERIA");
        labelUserMateriaText1.setToolTipText("");

        buttonActualizarMat.setText("Actualizar");
        buttonActualizarMat.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(labelUserMateriaText1)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(buttonAgregarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonActualizarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxParaFiltrarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBuscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBuscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(buttonVolverMat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelUserMateriaText1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonActualizarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxParaFiltrarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldBuscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(buttonVolverMat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscarMatActionPerformed

    private void textFieldNombreMatAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textFieldNombreMatAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreMatAncestorRemoved

    private void textFieldNombreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreMatActionPerformed

    private void textFieldApellidoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldApellidoMatActionPerformed

    private void buttonAgregarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgregarMatActionPerformed

    private void ComboBoxParaFiltrarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxParaFiltrarMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxParaFiltrarMatActionPerformed

    private void comboBoxCarreraMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCarreraMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCarreraMatActionPerformed

                                                    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxParaFiltrarMat;
    private javax.swing.JButton buttonActualizarMat;
    private javax.swing.JButton buttonAgregarMat;
    private javax.swing.JButton buttonBuscarMat;
    private javax.swing.JButton buttonVolverMat;
    private javax.swing.JComboBox<String> comboBoxCarreraMat;
    private javax.swing.JComboBox<String> comboBoxDecanatoMat;
    private javax.swing.JComboBox<String> comboBoxProfesorMat;
    private javax.swing.JComboBox<String> comboBoxSemestreMat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMateriaText2;
    private javax.swing.JLabel labelUserMateriaText1;
    private javax.swing.JPanel panelMateria;
    private javax.swing.JTable tableMateria;
    private javax.swing.JTextField textFieldApellidoMat;
    private javax.swing.JTextField textFieldBuscarMat;
    private javax.swing.JTextField textFieldNombreMat;
    // End of variables declaration//GEN-END:variables
}
