/*
Hanuman Sánchez CI: 28.316.086
Anthony Moreno CI: 28.204.620
Angel Goyo CI: 29.737.583
Miller Arias CI: 29.561.941
Luis Ochoa CI: 29.778.672
*/
package notarius.views;

/**
 *
 * @author ANGELITE
 */
public class AdminGestionSemestreView extends javax.swing.JPanel {

    /**
     * Creates new form LoginView
     */
    public AdminGestionSemestreView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonActualizarSem = new javax.swing.JButton();
        buttonAgregarSem = new javax.swing.JButton();
        panelSeccion = new javax.swing.JPanel();
        textFieldSemestre = new javax.swing.JTextField();
        labelSeccionText2 = new javax.swing.JLabel();
        textFieldFechIniSem = new javax.swing.JTextField();
        textFieldFechActSem = new javax.swing.JTextField();
        textFieldFechFinSem = new javax.swing.JTextField();
        textFieldBuscarSem = new javax.swing.JTextField();
        ComboBoxParaFiltrarSem = new javax.swing.JComboBox<>();
        buttonVolverSem = new javax.swing.JButton();
        labelUserSeccionText1 = new javax.swing.JLabel();
        buttonBuscarSem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(840, 631));

        buttonActualizarSem.setText("Actualizar");
        buttonActualizarSem.setBorder(new javax.swing.border.MatteBorder(null));

        buttonAgregarSem.setText("Agregar");
        buttonAgregarSem.setBorder(new javax.swing.border.MatteBorder(null));
        buttonAgregarSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarSemActionPerformed(evt);
            }
        });

        panelSeccion.setBackground(new java.awt.Color(153, 153, 153));
        panelSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFieldSemestre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semestre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldSemestre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                textFieldSemestreAncestorRemoved(evt);
            }
        });
        textFieldSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSemestreActionPerformed(evt);
            }
        });

        labelSeccionText2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSeccionText2.setText("REGISTRO");

        textFieldFechIniSem.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textFieldFechIniSem.setToolTipText("");
        textFieldFechIniSem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Inicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldFechIniSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFechIniSemActionPerformed(evt);
            }
        });

        textFieldFechActSem.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textFieldFechActSem.setToolTipText("");
        textFieldFechActSem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldFechActSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFechActSemActionPerformed(evt);
            }
        });

        textFieldFechFinSem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Final", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldFechFinSem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                textFieldFechFinSemAncestorRemoved(evt);
            }
        });
        textFieldFechFinSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFechFinSemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeccionLayout = new javax.swing.GroupLayout(panelSeccion);
        panelSeccion.setLayout(panelSeccionLayout);
        panelSeccionLayout.setHorizontalGroup(
            panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSeccionText2)
                .addGap(63, 63, 63))
            .addGroup(panelSeccionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldFechFinSem)
                        .addComponent(textFieldFechActSem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(textFieldFechIniSem)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelSeccionLayout.setVerticalGroup(
            panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeccionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelSeccionText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldFechIniSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldFechFinSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldFechActSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        textFieldBuscarSem.setText("Buscar...");
        textFieldBuscarSem.setBorder(new javax.swing.border.MatteBorder(null));
        textFieldBuscarSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarSemActionPerformed(evt);
            }
        });

        ComboBoxParaFiltrarSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por", "DECANATO", " " }));
        ComboBoxParaFiltrarSem.setToolTipText(""); // NOI18N
        ComboBoxParaFiltrarSem.setBorder(new javax.swing.border.MatteBorder(null));
        ComboBoxParaFiltrarSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxParaFiltrarSemActionPerformed(evt);
            }
        });

        buttonVolverSem.setText("VOLVER");
        buttonVolverSem.setBorder(new javax.swing.border.MatteBorder(null));

        labelUserSeccionText1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUserSeccionText1.setText("GESTION DE SEMESTRE");
        labelUserSeccionText1.setToolTipText("");

        buttonBuscarSem.setText("Buscar");
        buttonBuscarSem.setBorder(new javax.swing.border.MatteBorder(null));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2023-2", "01-07-2023", "01-03-2024", "20-02-2023", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Semestre", "FechaInit", "FechaFin", "FechaAct", "..."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(labelUserSeccionText1)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(buttonAgregarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonActualizarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxParaFiltrarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBuscarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBuscarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(panelSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(buttonVolverSem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1)))))
                        .addGap(11, 11, 11)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelUserSeccionText1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonActualizarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxParaFiltrarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldBuscarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarSem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(buttonVolverSem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgregarSemActionPerformed

    private void textFieldSemestreAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textFieldSemestreAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSemestreAncestorRemoved

    private void textFieldSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSemestreActionPerformed

    private void textFieldFechIniSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFechIniSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFechIniSemActionPerformed

    private void textFieldBuscarSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscarSemActionPerformed

    private void ComboBoxParaFiltrarSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxParaFiltrarSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxParaFiltrarSemActionPerformed

    private void textFieldFechActSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFechActSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFechActSemActionPerformed

    private void textFieldFechFinSemAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textFieldFechFinSemAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFechFinSemAncestorRemoved

    private void textFieldFechFinSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFechFinSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFechFinSemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxParaFiltrarSem;
    private javax.swing.JButton buttonActualizarSem;
    private javax.swing.JButton buttonAgregarSem;
    private javax.swing.JButton buttonBuscarSem;
    private javax.swing.JButton buttonVolverSem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelSeccionText2;
    private javax.swing.JLabel labelUserSeccionText1;
    private javax.swing.JPanel panelSeccion;
    private javax.swing.JTextField textFieldBuscarSem;
    private javax.swing.JTextField textFieldFechActSem;
    private javax.swing.JTextField textFieldFechFinSem;
    private javax.swing.JTextField textFieldFechIniSem;
    private javax.swing.JTextField textFieldSemestre;
    // End of variables declaration//GEN-END:variables
}
