// /*
// Hanuman Sánchez CI: 28.316.086
// Anthony Moreno CI: 28.204.620
// Angel Goyo CI: 29.737.583
// Miller Arias CI: 29.561.941
// Luis Ochoa CI: 29.778.672
// */
// package ucla.lab.notarius.views;

// import java.io.InputStream;
// import java.sql.Connection;
// import java.sql.DriverManager;
// import java.util.HashMap;
// import java.util.Map;

// import net.sf.jasperreports.engine.JasperCompileManager;
// import net.sf.jasperreports.engine.JasperFillManager;
// import net.sf.jasperreports.engine.JasperPrint;
// import net.sf.jasperreports.engine.JasperReport;
// import net.sf.jasperreports.view.JasperViewer;
// import ucla.lab.notarius.models.Estudiante;

// /**
//  *
//  * @author ANGELITE
//  */
// public class IndexEstudianteView extends javax.swing.JFrame {

//     /**
//      * Creates new form LoginView
//      */
//     public IndexEstudianteView() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jFrame1 = new javax.swing.JFrame();
//         jPanel1 = new javax.swing.JPanel();
//         buttonBuscarEst1 = new javax.swing.JButton();
//         panelUsuario1 = new javax.swing.JPanel();
//         textFieldNombreUs1 = new javax.swing.JTextField();
//         labelDecanatoText4 = new javax.swing.JLabel();
//         textFieldApellidoUs1 = new javax.swing.JTextField();
//         textFieldEstadoUs1 = new javax.swing.JTextField();
//         textFieldEstadUs1 = new javax.swing.JTextField();
//         textFieldContraUs1 = new javax.swing.JTextField();
//         jCheckBox4 = new javax.swing.JCheckBox();
//         jCheckBox5 = new javax.swing.JCheckBox();
//         jCheckBox6 = new javax.swing.JCheckBox();
//         labelDecanatoText5 = new javax.swing.JLabel();
//         buttonAgregarEst1 = new javax.swing.JButton();
//         ComboBoxParaFiltrarEst1 = new javax.swing.JComboBox<>();
//         labelUserEstudianteText2 = new javax.swing.JLabel();
//         buttonActualizarEst2 = new javax.swing.JButton();
//         textFieldBuscarEst1 = new javax.swing.JTextField();
//         buttonVolverEst1 = new javax.swing.JButton();
//         jScrollPane2 = new javax.swing.JScrollPane();
//         tableUsuario1 = new javax.swing.JTable();
//         buttonActualizarEst3 = new javax.swing.JButton();
//         inscribirBtn1 = new javax.swing.JButton();
//         buttonBuscarEst = new javax.swing.JButton();
//         panelUsuario = new javax.swing.JPanel();
//         textFieldNombreUs = new javax.swing.JTextField();
//         labelDecanatoText2 = new javax.swing.JLabel();
//         textFieldApellidoUs = new javax.swing.JTextField();
//         textFieldEstadoUs = new javax.swing.JTextField();
//         textFieldEstadUs = new javax.swing.JTextField();
//         textFieldContraUs = new javax.swing.JTextField();
//         jCheckBox1 = new javax.swing.JCheckBox();
//         jCheckBox2 = new javax.swing.JCheckBox();
//         jCheckBox3 = new javax.swing.JCheckBox();
//         labelDecanatoText3 = new javax.swing.JLabel();
//         buttonAgregarEst = new javax.swing.JButton();
//         ComboBoxParaFiltrarEst = new javax.swing.JComboBox<>();
//         labelUserEstudianteText1 = new javax.swing.JLabel();
//         buttonActualizarEst = new javax.swing.JButton();
//         textFieldBuscarEst = new javax.swing.JTextField();
//         buttonVolverEst = new javax.swing.JButton();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         tableUsuario = new javax.swing.JTable();
//         buttonActualizarEst1 = new javax.swing.JButton();
//         inscribirBtn = new javax.swing.JButton();

//         jPanel1.setBackground(new java.awt.Color(204, 204, 204));
//         jPanel1.setPreferredSize(new java.awt.Dimension(840, 631));

//         buttonBuscarEst1.setText("Buscar");
//         buttonBuscarEst1.setBorder(new javax.swing.border.MatteBorder(null));

//         panelUsuario1.setBackground(new java.awt.Color(153, 153, 153));
//         panelUsuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

//         textFieldNombreUs1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldNombreUs1.addAncestorListener(new javax.swing.event.AncestorListener() {
//             public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
//             }
//             public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
//             }
//             public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
//                 textFieldNombreUs1AncestorRemoved(evt);
//             }
//         });
//         textFieldNombreUs1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldNombreUs1ActionPerformed(evt);
//             }
//         });

//         labelDecanatoText4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//         labelDecanatoText4.setText("REGISTRO");

//         textFieldApellidoUs1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldApellidoUs1.setToolTipText("");
//         textFieldApellidoUs1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldApellidoUs1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldApellidoUs1ActionPerformed(evt);
//             }
//         });

//         textFieldEstadoUs1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldEstadoUs1.setToolTipText("");
//         textFieldEstadoUs1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldEstadoUs1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldEstadoUs1ActionPerformed(evt);
//             }
//         });

//         textFieldEstadUs1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldEstadUs1.setToolTipText("");
//         textFieldEstadUs1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldEstadUs1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldEstadUs1ActionPerformed(evt);
//             }
//         });

//         textFieldContraUs1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldContraUs1.setToolTipText("");
//         textFieldContraUs1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldContraUs1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldContraUs1ActionPerformed(evt);
//             }
//         });

//         jCheckBox4.setText("Admin");

//         jCheckBox5.setText("Usuario");

//         jCheckBox6.setText("Profesor");

//         labelDecanatoText5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//         labelDecanatoText5.setText("PERMISOS");

//         javax.swing.GroupLayout panelUsuario1Layout = new javax.swing.GroupLayout(panelUsuario1);
//         panelUsuario1.setLayout(panelUsuario1Layout);
//         panelUsuario1Layout.setHorizontalGroup(
//             panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(panelUsuario1Layout.createSequentialGroup()
//                 .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(panelUsuario1Layout.createSequentialGroup()
//                         .addGap(17, 17, 17)
//                         .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                 .addComponent(textFieldNombreUs1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
//                                 .addComponent(textFieldApellidoUs1))
//                             .addComponent(textFieldEstadoUs1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(textFieldEstadUs1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(textFieldContraUs1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addGroup(panelUsuario1Layout.createSequentialGroup()
//                                 .addComponent(jCheckBox4)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(jCheckBox5)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(jCheckBox6))))
//                     .addGroup(panelUsuario1Layout.createSequentialGroup()
//                         .addGap(63, 63, 63)
//                         .addComponent(labelDecanatoText4))
//                     .addGroup(panelUsuario1Layout.createSequentialGroup()
//                         .addGap(65, 65, 65)
//                         .addComponent(labelDecanatoText5)))
//                 .addContainerGap(20, Short.MAX_VALUE))
//         );
//         panelUsuario1Layout.setVerticalGroup(
//             panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(panelUsuario1Layout.createSequentialGroup()
//                 .addGap(18, 18, 18)
//                 .addComponent(labelDecanatoText4)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldNombreUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldApellidoUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldEstadoUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldContraUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addComponent(textFieldEstadUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(labelDecanatoText5)
//                 .addGap(3, 3, 3)
//                 .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jCheckBox4)
//                     .addComponent(jCheckBox5)
//                     .addComponent(jCheckBox6))
//                 .addContainerGap(21, Short.MAX_VALUE))
//         );

//         buttonAgregarEst1.setText("Agregar");
//         buttonAgregarEst1.setBorder(new javax.swing.border.MatteBorder(null));
//         buttonAgregarEst1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 buttonAgregarEst1ActionPerformed(evt);
//             }
//         });

//         ComboBoxParaFiltrarEst1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por", "DECANATO", " " }));
//         ComboBoxParaFiltrarEst1.setToolTipText(""); // NOI18N
//         ComboBoxParaFiltrarEst1.setBorder(new javax.swing.border.MatteBorder(null));
//         ComboBoxParaFiltrarEst1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 ComboBoxParaFiltrarEst1ActionPerformed(evt);
//             }
//         });

//         labelUserEstudianteText2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
//         labelUserEstudianteText2.setText("GESTION DE USUARIO");
//         labelUserEstudianteText2.setToolTipText("");

//         buttonActualizarEst2.setText("Eliminar");
//         buttonActualizarEst2.setBorder(new javax.swing.border.MatteBorder(null));

//         textFieldBuscarEst1.setText(" Buscar...");
//         textFieldBuscarEst1.setBorder(new javax.swing.border.MatteBorder(null));
//         textFieldBuscarEst1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldBuscarEst1ActionPerformed(evt);
//             }
//         });

//         buttonVolverEst1.setText("VOLVER");
//         buttonVolverEst1.setBorder(new javax.swing.border.MatteBorder(null));
//         buttonVolverEst1.addMouseListener(new java.awt.event.MouseAdapter() {
//             public void mouseClicked(java.awt.event.MouseEvent evt) {
//                 buttonVolverEst1MouseClicked(evt);
//             }
//         });

//         tableUsuario1.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null}
//             },
//             new String [] {
//                 "ID", "Usuario", "Nombre", "Apellido", "Contraseña", "Estado", "..."
//             }
//         ));
//         jScrollPane2.setViewportView(tableUsuario1);

//         buttonActualizarEst3.setText("Actualizar");
//         buttonActualizarEst3.setBorder(new javax.swing.border.MatteBorder(null));

//         inscribirBtn1.setText("Estudiante Por Carrera");
//         inscribirBtn1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 inscribirBtn1ActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                 .addGap(0, 0, Short.MAX_VALUE)
//                 .addComponent(labelUserEstudianteText2)
//                 .addGap(268, 268, 268))
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addGap(27, 27, 27)
//                         .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addGroup(jPanel1Layout.createSequentialGroup()
//                                 .addComponent(buttonAgregarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(buttonActualizarEst3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                             .addComponent(buttonActualizarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addComponent(ComboBoxParaFiltrarEst1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGap(18, 18, 18)
//                         .addComponent(textFieldBuscarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(buttonBuscarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addGap(86, 86, 86)
//                         .addComponent(inscribirBtn1)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(buttonVolverEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addContainerGap(31, Short.MAX_VALUE))
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addGap(58, 58, 58)
//                 .addComponent(labelUserEstudianteText2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(ComboBoxParaFiltrarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(textFieldBuscarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(buttonBuscarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(buttonVolverEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(inscribirBtn1))
//                         .addGap(42, 42, 42))
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(buttonActualizarEst3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(buttonAgregarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(buttonActualizarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(71, 71, 71))))
//         );

//         javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
//         jFrame1.getContentPane().setLayout(jFrame1Layout);
//         jFrame1Layout.setHorizontalGroup(
//             jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGap(0, 400, Short.MAX_VALUE)
//             .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                 .addGroup(jFrame1Layout.createSequentialGroup()
//                     .addGap(0, 0, Short.MAX_VALUE)
//                     .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addGap(0, 0, Short.MAX_VALUE)))
//         );
//         jFrame1Layout.setVerticalGroup(
//             jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGap(0, 300, Short.MAX_VALUE)
//             .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                 .addGroup(jFrame1Layout.createSequentialGroup()
//                     .addGap(0, 0, Short.MAX_VALUE)
//                     .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addGap(0, 0, Short.MAX_VALUE)))
//         );

//         setBackground(new java.awt.Color(204, 204, 204));
//         setPreferredSize(new java.awt.Dimension(840, 631));

//         buttonBuscarEst.setText("Buscar");
//         buttonBuscarEst.setBorder(new javax.swing.border.MatteBorder(null));

//         panelUsuario.setBackground(new java.awt.Color(153, 153, 153));
//         panelUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

//         textFieldNombreUs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldNombreUs.addAncestorListener(new javax.swing.event.AncestorListener() {
//             public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
//             }
//             public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
//             }
//             public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
//                 textFieldNombreUsAncestorRemoved(evt);
//             }
//         });
//         textFieldNombreUs.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldNombreUsActionPerformed(evt);
//             }
//         });

//         labelDecanatoText2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//         labelDecanatoText2.setText("REGISTRO");

//         textFieldApellidoUs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldApellidoUs.setToolTipText("");
//         textFieldApellidoUs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldApellidoUs.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldApellidoUsActionPerformed(evt);
//             }
//         });

//         textFieldEstadoUs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldEstadoUs.setToolTipText("");
//         textFieldEstadoUs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldEstadoUs.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldEstadoUsActionPerformed(evt);
//             }
//         });

//         textFieldEstadUs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldEstadUs.setToolTipText("");
//         textFieldEstadUs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldEstadUs.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldEstadUsActionPerformed(evt);
//             }
//         });

//         textFieldContraUs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
//         textFieldContraUs.setToolTipText("");
//         textFieldContraUs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
//         textFieldContraUs.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldContraUsActionPerformed(evt);
//             }
//         });

//         jCheckBox1.setText("Admin");

//         jCheckBox2.setText("Usuario");

//         jCheckBox3.setText("Profesor");

//         labelDecanatoText3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//         labelDecanatoText3.setText("PERMISOS");

//         javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
//         panelUsuario.setLayout(panelUsuarioLayout);
//         panelUsuarioLayout.setHorizontalGroup(
//             panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(panelUsuarioLayout.createSequentialGroup()
//                 .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(panelUsuarioLayout.createSequentialGroup()
//                         .addGap(17, 17, 17)
//                         .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                 .addComponent(textFieldNombreUs, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
//                                 .addComponent(textFieldApellidoUs))
//                             .addComponent(textFieldEstadoUs, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(textFieldEstadUs, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(textFieldContraUs, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addGroup(panelUsuarioLayout.createSequentialGroup()
//                                 .addComponent(jCheckBox1)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(jCheckBox2)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(jCheckBox3))))
//                     .addGroup(panelUsuarioLayout.createSequentialGroup()
//                         .addGap(63, 63, 63)
//                         .addComponent(labelDecanatoText2))
//                     .addGroup(panelUsuarioLayout.createSequentialGroup()
//                         .addGap(65, 65, 65)
//                         .addComponent(labelDecanatoText3)))
//                 .addContainerGap(20, Short.MAX_VALUE))
//         );
//         panelUsuarioLayout.setVerticalGroup(
//             panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(panelUsuarioLayout.createSequentialGroup()
//                 .addGap(18, 18, 18)
//                 .addComponent(labelDecanatoText2)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldNombreUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldApellidoUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldEstadoUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(textFieldContraUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addComponent(textFieldEstadUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(labelDecanatoText3)
//                 .addGap(3, 3, 3)
//                 .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jCheckBox1)
//                     .addComponent(jCheckBox2)
//                     .addComponent(jCheckBox3))
//                 .addContainerGap(21, Short.MAX_VALUE))
//         );

//         buttonAgregarEst.setText("Agregar");
//         buttonAgregarEst.setBorder(new javax.swing.border.MatteBorder(null));
//         buttonAgregarEst.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 buttonAgregarEstActionPerformed(evt);
//             }
//         });

//         ComboBoxParaFiltrarEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por", "DECANATO", " " }));
//         ComboBoxParaFiltrarEst.setToolTipText(""); // NOI18N
//         ComboBoxParaFiltrarEst.setBorder(new javax.swing.border.MatteBorder(null));
//         ComboBoxParaFiltrarEst.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 ComboBoxParaFiltrarEstActionPerformed(evt);
//             }
//         });

//         labelUserEstudianteText1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
//         labelUserEstudianteText1.setText("GESTION DE USUARIO");
//         labelUserEstudianteText1.setToolTipText("");

//         buttonActualizarEst.setText("Eliminar");
//         buttonActualizarEst.setBorder(new javax.swing.border.MatteBorder(null));

//         textFieldBuscarEst.setText(" Buscar...");
//         textFieldBuscarEst.setBorder(new javax.swing.border.MatteBorder(null));
//         textFieldBuscarEst.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 textFieldBuscarEstActionPerformed(evt);
//             }
//         });

//         buttonVolverEst.setText("VOLVER");
//         buttonVolverEst.setBorder(new javax.swing.border.MatteBorder(null));
//         buttonVolverEst.addMouseListener(new java.awt.event.MouseAdapter() {
//             public void mouseClicked(java.awt.event.MouseEvent evt) {
//                 buttonVolverEstMouseClicked(evt);
//             }
//         });

//         tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null}
//             },
//             new String [] {
//                 "ID", "Usuario", "Nombre", "Apellido", "Contraseña", "Estado", "..."
//             }
//         ));
//         jScrollPane1.setViewportView(tableUsuario);

//         buttonActualizarEst1.setText("Actualizar");
//         buttonActualizarEst1.setBorder(new javax.swing.border.MatteBorder(null));

//         inscribirBtn.setText("Estudiante Por Carrera");
//         inscribirBtn.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 inscribirBtnActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                 .addGap(0, 0, Short.MAX_VALUE)
//                 .addComponent(labelUserEstudianteText1)
//                 .addGap(268, 268, 268))
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGap(27, 27, 27)
//                         .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addGroup(layout.createSequentialGroup()
//                                 .addComponent(buttonAgregarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(buttonActualizarEst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                             .addComponent(buttonActualizarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(ComboBoxParaFiltrarEst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGap(18, 18, 18)
//                         .addComponent(textFieldBuscarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(buttonBuscarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGap(86, 86, 86)
//                         .addComponent(inscribirBtn)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(buttonVolverEst, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addContainerGap(31, Short.MAX_VALUE))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGap(58, 58, 58)
//                 .addComponent(labelUserEstudianteText1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(ComboBoxParaFiltrarEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(textFieldBuscarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(buttonBuscarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(buttonVolverEst, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(inscribirBtn))
//                         .addGap(42, 42, 42))
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(buttonActualizarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(buttonAgregarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(buttonActualizarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(71, 71, 71))))
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void textFieldNombreUsAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textFieldNombreUsAncestorRemoved
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldNombreUsAncestorRemoved

//     private void textFieldNombreUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreUsActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldNombreUsActionPerformed

//     private void textFieldApellidoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidoUsActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldApellidoUsActionPerformed

//     private void textFieldEstadoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEstadoUsActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldEstadoUsActionPerformed

//     private void buttonAgregarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarEstActionPerformed
//         //AGREGAR USUARIO
//         String nombre = this.textFieldNombreUs.getText();
//         String apellido = this.textFieldApellidoUs.getName();
//         String cedula = this.textFieldEstadoUs.getText();
//         String password = this.textFieldContraUs.getText();
//         String carreraName = this.textFieldEstadUs.getText();
        
        
//         Estudiante estudiante = new Estudiante();
//         estudiante.setNombres(nombre);
//         estudiante.setApellidos(apellido);
//         estudiante.setCedula(cedula);
//         estudiante.setClave(password);

        
//         Controller control = null;
//         control = new Controller();
//         control.estudiante.registrar(estudiante);
        
        
//     }//GEN-LAST:event_buttonAgregarEstActionPerformed

//     private void ComboBoxParaFiltrarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxParaFiltrarEstActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_ComboBoxParaFiltrarEstActionPerformed

//     private void textFieldBuscarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarEstActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldBuscarEstActionPerformed

//     private void textFieldEstadUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEstadUsActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldEstadUsActionPerformed

//     private void textFieldContraUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContraUsActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldContraUsActionPerformed

//     private void inscribirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirBtnActionPerformed
//         // MOSTRAR REPORTE
//         try {
//             Class.forName("org.postgresql.Driver");
//             try (Connection con = DriverManager.getConnection("jdbc:postgresql://[YOURHOST]:[YOURPORT]/[YOURDB]", "[YOURDBUSER]", "[YOURDBPASSWORD]")) {
//                 InputStream reportStream = getClass().getClassLoader().getResourceAsStream("jasper/[YOURREPORT].jrxml");
//                 JasperReport jr = JasperCompileManager.compileReport(reportStream);

//                 Map<String, Object> parameters = new HashMap<>();

//                 parameters.put("[YOURPARAM]", null);

//                 JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
//                 JasperViewer.viewReport(jp);
//             }
//         } catch (Exception ex) {
//             ex.printStackTrace();
//         }
        
        
//     }//GEN-LAST:event_inscribirBtnActionPerformed

//     private void buttonVolverEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverEstMouseClicked
//         MenuPrincipal menuPrincipal = new MenuPrincipal();
//         menuPrincipal.setVisible(true);
//         menuPrincipal.setLocationRelativeTo(null);
//         this.dispose();
//     }//GEN-LAST:event_buttonVolverEstMouseClicked

//     private void textFieldNombreUs1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textFieldNombreUs1AncestorRemoved
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldNombreUs1AncestorRemoved

//     private void textFieldNombreUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreUs1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldNombreUs1ActionPerformed

//     private void textFieldApellidoUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidoUs1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldApellidoUs1ActionPerformed

//     private void textFieldEstadoUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEstadoUs1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldEstadoUs1ActionPerformed

//     private void textFieldEstadUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEstadUs1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldEstadUs1ActionPerformed

//     private void textFieldContraUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContraUs1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldContraUs1ActionPerformed

//     private void buttonAgregarEst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarEst1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_buttonAgregarEst1ActionPerformed

//     private void ComboBoxParaFiltrarEst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxParaFiltrarEst1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_ComboBoxParaFiltrarEst1ActionPerformed

//     private void textFieldBuscarEst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarEst1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_textFieldBuscarEst1ActionPerformed

//     private void buttonVolverEst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverEst1MouseClicked
//         // TODO add your handling code here:
//     }//GEN-LAST:event_buttonVolverEst1MouseClicked

//     private void inscribirBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirBtn1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_inscribirBtn1ActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JComboBox<String> ComboBoxParaFiltrarEst;
//     private javax.swing.JComboBox<String> ComboBoxParaFiltrarEst1;
//     private javax.swing.JButton buttonActualizarEst;
//     private javax.swing.JButton buttonActualizarEst1;
//     private javax.swing.JButton buttonActualizarEst2;
//     private javax.swing.JButton buttonActualizarEst3;
//     private javax.swing.JButton buttonAgregarEst;
//     private javax.swing.JButton buttonAgregarEst1;
//     private javax.swing.JButton buttonBuscarEst;
//     private javax.swing.JButton buttonBuscarEst1;
//     private javax.swing.JButton buttonVolverEst;
//     private javax.swing.JButton buttonVolverEst1;
//     private javax.swing.JButton inscribirBtn;
//     private javax.swing.JButton inscribirBtn1;
//     private javax.swing.JCheckBox jCheckBox1;
//     private javax.swing.JCheckBox jCheckBox2;
//     private javax.swing.JCheckBox jCheckBox3;
//     private javax.swing.JCheckBox jCheckBox4;
//     private javax.swing.JCheckBox jCheckBox5;
//     private javax.swing.JCheckBox jCheckBox6;
//     private javax.swing.JFrame jFrame1;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JScrollPane jScrollPane2;
//     private javax.swing.JLabel labelDecanatoText2;
//     private javax.swing.JLabel labelDecanatoText3;
//     private javax.swing.JLabel labelDecanatoText4;
//     private javax.swing.JLabel labelDecanatoText5;
//     private javax.swing.JLabel labelUserEstudianteText1;
//     private javax.swing.JLabel labelUserEstudianteText2;
//     private javax.swing.JPanel panelUsuario;
//     private javax.swing.JPanel panelUsuario1;
//     private javax.swing.JTable tableUsuario;
//     private javax.swing.JTable tableUsuario1;
//     private javax.swing.JTextField textFieldApellidoUs;
//     private javax.swing.JTextField textFieldApellidoUs1;
//     private javax.swing.JTextField textFieldBuscarEst;
//     private javax.swing.JTextField textFieldBuscarEst1;
//     private javax.swing.JTextField textFieldContraUs;
//     private javax.swing.JTextField textFieldContraUs1;
//     private javax.swing.JTextField textFieldEstadUs;
//     private javax.swing.JTextField textFieldEstadUs1;
//     private javax.swing.JTextField textFieldEstadoUs;
//     private javax.swing.JTextField textFieldEstadoUs1;
//     private javax.swing.JTextField textFieldNombreUs;
//     private javax.swing.JTextField textFieldNombreUs1;
//     // End of variables declaration//GEN-END:variables
// }
