/*
Hanuman Sánchez CI: 28.316.086
Anthony Moreno CI: 28.204.620
Angel Goyo CI: 29.737.583
Miller Arias CI: 29.561.941
Luis Ochoa CI: 29.778.672
*/
package ucla.lab.notarius.views;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;

import javax.swing.DefaultListModel;


/**
 *
 * @author ANGELITE
 */
public class InscripcionView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public InscripcionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        panelUsuario2 = new javax.swing.JPanel();
        textFieldNombreUs2 = new javax.swing.JTextField();
        labelDecanatoText4 = new javax.swing.JLabel();
        textFieldApellidoUs2 = new javax.swing.JTextField();
        textFieldEstadoUs2 = new javax.swing.JTextField();
        buttonVolverEst7 = new javax.swing.JButton();
        buttonVolverEst8 = new javax.swing.JButton();
        labelUserEstudianteText3 = new javax.swing.JLabel();
        ComboBoxParaFiltrarEst2 = new javax.swing.JComboBox<>();
        buttonBuscarEst2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUsuario2 = new javax.swing.JTable();
        buttonVolverEst4 = new javax.swing.JButton();
        buttonVolverEst9 = new javax.swing.JButton();
        buttonVolverEst10 = new javax.swing.JButton();
        panelUsuario1 = new javax.swing.JPanel();
        textBoxNombre = new javax.swing.JTextField();
        textBoxApellido = new javax.swing.JTextField();
        textBoxCedula = new javax.swing.JTextField();
        buttonCargarEstudiante = new javax.swing.JButton();
        limpiarCampos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        seccionesElegidasList = new javax.swing.JList<>();
        materiasCombobox = new javax.swing.JComboBox<>();
        seccionesComboBox = new javax.swing.JComboBox<>();
        agregarSeccionButton = new javax.swing.JButton();
        inscribirButton = new javax.swing.JButton();
        lapsoAcademico = new javax.swing.JComboBox<>();
        labelUserEstudianteText2 = new javax.swing.JLabel();
        buttonVolver = new javax.swing.JButton();
        imprimirtButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 631));

        panelUsuario2.setBackground(new java.awt.Color(153, 153, 153));
        panelUsuario2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFieldNombreUs2.setEditable(false);
        textFieldNombreUs2.setText("JUAN CANUTO");
        textFieldNombreUs2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldNombreUs2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                textFieldNombreUs2AncestorRemoved(evt);
            }
        });
        textFieldNombreUs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreUs2ActionPerformed(evt);
            }
        });

        labelDecanatoText4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDecanatoText4.setText("REGISTRO");

        textFieldApellidoUs2.setEditable(false);
        textFieldApellidoUs2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textFieldApellidoUs2.setText("PEREZ CHAVEZ");
        textFieldApellidoUs2.setToolTipText("");
        textFieldApellidoUs2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldApellidoUs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidoUs2ActionPerformed(evt);
            }
        });

        textFieldEstadoUs2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textFieldEstadoUs2.setToolTipText("");
        textFieldEstadoUs2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textFieldEstadoUs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEstadoUs2ActionPerformed(evt);
            }
        });

        buttonVolverEst7.setText("CARGAR");
        buttonVolverEst7.setBorder(new javax.swing.border.MatteBorder(null));

        buttonVolverEst8.setText("LIMPIAR");
        buttonVolverEst8.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout panelUsuario2Layout = new javax.swing.GroupLayout(panelUsuario2);
        panelUsuario2.setLayout(panelUsuario2Layout);
        panelUsuario2Layout.setHorizontalGroup(
            panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario2Layout.createSequentialGroup()
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuario2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelDecanatoText4))
                    .addGroup(panelUsuario2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuario2Layout.createSequentialGroup()
                                .addComponent(buttonVolverEst7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonVolverEst8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldApellidoUs2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(textFieldNombreUs2)
                                .addComponent(textFieldEstadoUs2)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelUsuario2Layout.setVerticalGroup(
            panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelDecanatoText4)
                .addGap(11, 11, 11)
                .addComponent(textFieldEstadoUs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldNombreUs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldApellidoUs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVolverEst7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVolverEst8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        labelUserEstudianteText3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUserEstudianteText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserEstudianteText3.setText("INSCRIPCIÓN ESTUDIANTE");
        labelUserEstudianteText3.setToolTipText("");

        ComboBoxParaFiltrarEst2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por", "estudiantes que retiraron alguna asignatura ", "estudiantes por carrera", "estudiantes por semestre", "20 mejores promedios por carrera", "20 mejores promedios por Decanat", "por género de carrera y Decanato", "estudiantes con promedios por encima de 16 puntos por sección y por carrera" }));
        ComboBoxParaFiltrarEst2.setToolTipText(""); // NOI18N
        ComboBoxParaFiltrarEst2.setBorder(new javax.swing.border.MatteBorder(null));
        ComboBoxParaFiltrarEst2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxParaFiltrarEst2ActionPerformed(evt);
            }
        });

        buttonBuscarEst2.setText("FILTRAR");
        buttonBuscarEst2.setBorder(new javax.swing.border.MatteBorder(null));

        tableUsuario2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CED_EST", "Usuario", "Nombre", "Apellido", "Contraseña", "Rol", "Estado", "..."
            }
        ));
        jScrollPane3.setViewportView(tableUsuario2);

        buttonVolverEst4.setText("VOLVER");
        buttonVolverEst4.setBorder(new javax.swing.border.MatteBorder(null));
        buttonVolverEst4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVolverEst4MouseClicked(evt);
            }
        });

        buttonVolverEst9.setText("Inscribir");
        buttonVolverEst9.setBorder(new javax.swing.border.MatteBorder(null));

        buttonVolverEst10.setText("Imprimir");
        buttonVolverEst10.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(labelUserEstudianteText3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxParaFiltrarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonBuscarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonVolverEst10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonVolverEst9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(buttonVolverEst4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(646, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelUserEstudianteText3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxParaFiltrarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBuscarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(panelUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVolverEst9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVolverEst10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(560, Short.MAX_VALUE)
                    .addComponent(buttonVolverEst4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(840, 631));

        panelUsuario1.setBackground(new java.awt.Color(153, 153, 153));
        panelUsuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textBoxNombre.setEditable(false);
        textBoxNombre.setText("JUAN CANUTO");
        textBoxNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textBoxNombre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                textBoxNombreAncestorRemoved(evt);
            }
        });
        textBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxNombreActionPerformed(evt);
            }
        });

        textBoxApellido.setEditable(false);
        textBoxApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textBoxApellido.setText("PEREZ CHAVEZ");
        textBoxApellido.setToolTipText("");
        textBoxApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textBoxApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxApellidoActionPerformed(evt);
            }
        });

        textBoxCedula.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        textBoxCedula.setToolTipText("");
        textBoxCedula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 11))); // NOI18N
        textBoxCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxCedulaActionPerformed(evt);
            }
        });

        buttonCargarEstudiante.setText("CARGAR");
        buttonCargarEstudiante.setBorder(new javax.swing.border.MatteBorder(null));

        limpiarCampos.setText("LIMPIAR");
        limpiarCampos.setBorder(new javax.swing.border.MatteBorder(null));
        limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCamposActionPerformed(evt);
            }
        });

        seccionesElegidasList.setDropMode(javax.swing.DropMode.INSERT);
        jScrollPane4.setViewportView(seccionesElegidasList);

        materiasCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia 1", "Materia 2", "Materia 3", "Materia 4" }));
        materiasCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasComboboxActionPerformed(evt);
            }
        });

        seccionesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secion 1", "Seccion 2" }));

        agregarSeccionButton.setText("Agregar");
        agregarSeccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSeccionButtonActionPerformed(evt);
            }
        });

        inscribirButton.setText("Inscribir");
        inscribirButton.setBorder(new javax.swing.border.MatteBorder(null));

        lapsoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024-I", "2024-II" }));
        lapsoAcademico.setToolTipText("");
        lapsoAcademico.setBorder(javax.swing.BorderFactory.createTitledBorder("Lapso Academico"));

        javax.swing.GroupLayout panelUsuario1Layout = new javax.swing.GroupLayout(panelUsuario1);
        panelUsuario1.setLayout(panelUsuario1Layout);
        panelUsuario1Layout.setHorizontalGroup(
            panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBoxCedula)
                    .addGroup(panelUsuario1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(limpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(buttonCargarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textBoxApellido)
                    .addComponent(textBoxNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(lapsoAcademico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                        .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuario1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(materiasCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seccionesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                        .addComponent(agregarSeccionButton)
                        .addGap(218, 218, 218))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inscribirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );
        panelUsuario1Layout.setVerticalGroup(
            panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBoxCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(materiasCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seccionesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuario1Layout.createSequentialGroup()
                        .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuario1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(buttonCargarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuario1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(agregarSeccionButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelUsuario1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(textBoxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lapsoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addGap(62, 62, 62)
                .addComponent(inscribirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        labelUserEstudianteText2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUserEstudianteText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserEstudianteText2.setText("Inscribir Estudiante");
        labelUserEstudianteText2.setToolTipText("");

        buttonVolver.setText("VOLVER");
        buttonVolver.setBorder(new javax.swing.border.MatteBorder(null));
        buttonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVolverMouseClicked(evt);
            }
        });

        imprimirtButton.setText("Imprimir");
        imprimirtButton.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(imprimirtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelUserEstudianteText2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUserEstudianteText2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimirtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        setBounds(800, 600, 937, 661);
    }// </editor-fold>//GEN-END:initComponents

    private void textBoxCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxCedulaActionPerformed

    private void textBoxApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxApellidoActionPerformed

    private void textBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxNombreActionPerformed

    private void textBoxNombreAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textBoxNombreAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxNombreAncestorRemoved

    private void buttonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        menuPrincipal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonVolverMouseClicked

    private void textFieldNombreUs2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textFieldNombreUs2AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreUs2AncestorRemoved

    private void textFieldNombreUs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreUs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreUs2ActionPerformed

    private void textFieldApellidoUs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidoUs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldApellidoUs2ActionPerformed

    private void textFieldEstadoUs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEstadoUs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEstadoUs2ActionPerformed

    private void ComboBoxParaFiltrarEst2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxParaFiltrarEst2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxParaFiltrarEst2ActionPerformed

    private void buttonVolverEst4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverEst4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverEst4MouseClicked

    private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed
    
                
    }//GEN-LAST:event_limpiarCamposActionPerformed

    private void agregarSeccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSeccionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarSeccionButtonActionPerformed

    private void materiasComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiasComboboxActionPerformed

    //getters
    public String getCedula() {
        return textBoxCedula.getText();
    }
    
    public String getNombre() {
        return textBoxNombre.getText();
    }
    
    public String getApellido() {
        return textBoxApellido.getText();
    }

    public String getSeleccionSeccionesComboBox() {
        return (String)seccionesComboBox.getSelectedItem();
    }

    //listeners
    public void submitCargarButton(ActionListener actionListener) {
        buttonCargarEstudiante.addActionListener(actionListener);
    }
    public void submitAgregarSeccionButton(ActionListener actionListener) {
        agregarSeccionButton.addActionListener(actionListener);
      
    }

    public void submitInscribirButton(ActionListener actionListener) {
        inscribirButton.addActionListener(actionListener);
      
    }

    public void submitMateriaSeccionada(ItemListener itemListener) {
        materiasCombobox.addItemListener(itemListener);
    }

    //setters
    public void setNombres (String nombres) {
        textBoxNombre.setText(nombres);

    }
    public void setApellidos (String apellidos) {
        textBoxApellido.setText(apellidos);
    }
    
    

    public void setseccionesElegidas(String[] seccionesElegidas) {
        seccionesElegidasList.setListData(seccionesElegidas);;
    }

    public void setComboBoxMaterias(String[] materias) {
        materiasCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(materias));
    }

    public void setComboBoxLapso(String[] lapsos) {
        lapsoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(lapsos));
    }

    public void setComboBoxSecciones(String[] secciones) {
        seccionesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(secciones));
    }

    public void addSeccionItem(String seccionItem) {
        seccionesComboBox.addItem(seccionItem);
       
    }

    public void seccionListAgregar(String item) {
        DefaultListModel<String> modelo = (DefaultListModel<String>)seccionesElegidasList.getModel();
        modelo.addElement(item);
    }

    public String getCodigo() {
        return (String)lapsoAcademico.getSelectedItem();
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxParaFiltrarEst2;
    private javax.swing.JButton agregarSeccionButton;
    private javax.swing.JButton buttonBuscarEst2;
    private javax.swing.JButton buttonCargarEstudiante;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JButton buttonVolverEst10;
    private javax.swing.JButton buttonVolverEst4;
    private javax.swing.JButton buttonVolverEst7;
    private javax.swing.JButton buttonVolverEst8;
    private javax.swing.JButton buttonVolverEst9;
    private javax.swing.JButton imprimirtButton;
    private javax.swing.JButton inscribirButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelDecanatoText4;
    private javax.swing.JLabel labelUserEstudianteText2;
    private javax.swing.JLabel labelUserEstudianteText3;
    private javax.swing.JComboBox<String> lapsoAcademico;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JComboBox<String> materiasCombobox;
    private javax.swing.JPanel panelUsuario1;
    private javax.swing.JPanel panelUsuario2;
    private javax.swing.JComboBox<String> seccionesComboBox;
    private javax.swing.JList<String> seccionesElegidasList;
    private javax.swing.JTable tableUsuario2;
    private javax.swing.JTextField textBoxApellido;
    private javax.swing.JTextField textBoxCedula;
    private javax.swing.JTextField textBoxNombre;
    private javax.swing.JTextField textFieldApellidoUs2;
    private javax.swing.JTextField textFieldEstadoUs2;
    private javax.swing.JTextField textFieldNombreUs2;
    // End of variables declaration//GEN-END:variables
}
