/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucla.lab.notarius.views;

/**
 *
 * @author Luis
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDecanatos = new javax.swing.JButton();
        buttonEstudiante = new javax.swing.JButton();
        jButtonSecciones = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonMaterias = new javax.swing.JButton();
        jButtonSemestre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonDecanatos.setText("DECANATOS");
        jButtonDecanatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDecanatosMouseClicked(evt);
            }
        });
        jButtonDecanatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecanatosActionPerformed(evt);
            }
        });

        buttonEstudiante.setText("ESTUDIANTES");
        buttonEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEstudianteMouseClicked(evt);
            }
        });
        buttonEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEstudianteActionPerformed(evt);
            }
        });

        jButtonSecciones.setText("SECCIONES");
        jButtonSecciones.setToolTipText("");
        jButtonSecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeccionesMouseClicked(evt);
            }
        });

        jButtonUsuarios.setText("USUARIOS");
        jButtonUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUsuariosMouseClicked(evt);
            }
        });
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });

        jButtonMaterias.setText("MATERIAS");
        jButtonMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMateriasMouseClicked(evt);
            }
        });

        jButtonSemestre.setText("SEMESTRE");
        jButtonSemestre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSemestreMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Menú Principal");

        jButtonCarrera.setText("CARRERAS");
        jButtonCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCarreraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jButtonDecanatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(buttonEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDecanatos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
        );

        setBounds(0, 0, 569, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonDecanatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDecanatosMouseClicked
        AdminGestionDecanatoView adminGestionDecanatoView = new AdminGestionDecanatoView();
        adminGestionDecanatoView.setVisible(true);
        adminGestionDecanatoView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonDecanatosMouseClicked

    private void buttonEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEstudianteMouseClicked
         GestionEstudianteView gestionEstudianteView = new GestionEstudianteView();
        gestionEstudianteView.setVisible(true);
        gestionEstudianteView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonEstudianteMouseClicked

    private void jButtonSeccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeccionesMouseClicked
        AdminGestionSeccionView adminGestionSeccionView = new AdminGestionSeccionView();
        adminGestionSeccionView.setVisible(true);
        adminGestionSeccionView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonSeccionesMouseClicked

    private void jButtonUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUsuariosMouseClicked
        AdminGestionUsuarioView adminGestionUsuarioView = new AdminGestionUsuarioView();
        adminGestionUsuarioView.setVisible(true);
        adminGestionUsuarioView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonUsuariosMouseClicked

    private void jButtonMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMateriasMouseClicked
        AdminGestionMateriaView adminGestionMateriaView = new AdminGestionMateriaView();
        adminGestionMateriaView.setVisible(true);
        adminGestionMateriaView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonMateriasMouseClicked

    private void jButtonSemestreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSemestreMouseClicked
        AdminGestionSemestreView adminGestionSemestreView = new AdminGestionSemestreView();
        adminGestionSemestreView.setVisible(true);
        adminGestionSemestreView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonSemestreMouseClicked

    private void jButtonDecanatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecanatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDecanatosActionPerformed

    private void jButtonCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCarreraMouseClicked
        AdminGestionCarreraView adminGestionCarreraView = new AdminGestionCarreraView();
        adminGestionCarreraView.setVisible(true);
        adminGestionCarreraView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonCarreraMouseClicked

    private void buttonEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEstudianteActionPerformed
    
    }//GEN-LAST:event_buttonEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEstudiante;
    private javax.swing.JButton jButtonCarrera;
    private javax.swing.JButton jButtonDecanatos;
    private javax.swing.JButton jButtonMaterias;
    private javax.swing.JButton jButtonSecciones;
    private javax.swing.JButton jButtonSemestre;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
